//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjOnlineBookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int BookID { get; set; }
        public string BookCover { get; set; }
        public string BookName { get; set; }
        public string BookAuthor { get; set; }
        public string BookPublisher { get; set; }
        public string BookYear { get; set; }
        public string BookGenre { get; set; }
        public Nullable<int> BookISBN { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
    }
}
