//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjOnlineBookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderID { get; set; }
        public string username { get; set; }
        public string shippingAddress { get; set; }
        public string shippingZipCode { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> priceTotal { get; set; }
        public string title { get; set; }
    }
}
